### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by ovhemert** [nearform/no-gres#11]
Add automated tests / CI?

Suggestion: Greenkeeper & Travis.

**Comment by mcollina** [comment]
+1 to both.

**Comment by mcollina** [comment]
Travis is configured.

**Comment by mcollina** [comment]
I'd set up greenkeeper after we have a working travis integration (tests are passing)

**Comment by ovhemert** [comment]
@mcollina can you add greenkeeper?

**Comment by mcollina** [comment]
Added

**Comment by ovhemert** [comment]
Thanks. I will merge PR #14 also to make sure Travis / Greenkeeper pick up `tap` tests first.
